server:
  error:
    include-stacktrace: never

spring:
  application:
    name: promecal
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=promecal;trustServerCertificate=true;sendTimeAsDateTime=false;
    username: sa
    password: 12345678
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.SQLServerDialect

api:
  security:
    secret: ${JWT_SECRET:secret}
logging:
  level:
    org.hibernate: DEBUG