server:
  error:
    include-stacktrace: never
  port: 8080

spring:
  application:
    name: promecal
  datasource:
    url: jdbc:postgresql://localhost:5432/promecal
    username: postgres
    password: benites1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  security:
    secret: ${JWT_SECRET:secret}
logging:
  level:
    org.hibernate: DEBUG