server:
  error:
    include-stacktrace: never
  port: 8080

spring:
  application:
    name: promecal
  datasource:
    url: jdbc:postgresql://ep-twilight-rice-a5xb2jia.us-east-2.aws.neon.tech/bd_promecal?user=bd_promecal_owner&password=7TngGZJkP8VB&sslmode=require
    driver-class-name: org.postgresql.Driver
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: jeffersonapromecal@gmail.com
    password: cgxa ciep gvkm liiq
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
api:
  security:
    secret: ${JWT_SECRET:secret}

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate: DEBUG